### PR TITLE
feat(nix): add nix flake

### PR DESCRIPTION
**Pull request by MaxKiv**
First of **thanks for your amazing repo!**
This is very similar to stuff I have been trying, and its great to have a source of inspiration ❤️

Since I am on Nixos, I added a nix flake to be able to build your firmware.
it is also very useful to obtain a development shell with the right toolchain on any system with the nix package manager installed. It points to the toolchain you defined in `rust-toolchain.toml`.

Maybe it is useful for the next person that wants to check out your repository, and is also using nix.

Since I am currently traveling I dont have enough data to check if `nix build` works. The nix dev shell does work, and I am able to build your package with `cargo build`, which is as far as I wanted to go.

### CODE REVIEW

**Comment by claudiomattera** [comment]
Thanks for the kind words :)
I am happy to hear this project is helping others.

I can see you changed the Rust toolchain to nightly from stable.
Is this required for building on Nix?

I would rather keep this project on stable Rust.

**Comment by MaxKiv** [comment]
Ah no that's my bad, any rust channel will work.
I changed it to stable

**Comment by claudiomattera** [comment]
Would you mind adding also some instructions on how to use it with Nix?

Maybe a short section in the Readme, between Connections and Changes?

~~~~~markdown
Usage with Nix
----

To use this project in a Nix environment run the following commands.

~~~~shell
nix run something
~~~~

Contributed by MaxKiv.
~~~~~

**Comment by MaxKiv** [comment]
Ofcourse! Would something like this be ok?
I also found time to fix the `nix build`

**Comment by claudiomattera** [comment]
Sorry for the delay, it has been some busy days.

I think all looks good.

I will try to find time to merge it during the weekend.
I also wanted to upgrade the `esp-*` dependencies, so I will probably merge to another branch, and only in the end to `master`.

Thanks again for your contribution :)

**Comment by claudiomattera** [comment]
Rebased and merged

**Pull request closed without merging**
